
import React from 'react';
import { motion } from 'framer-motion';
import { Activity, Zap, Thermometer, Waves, Info, ShieldCheck, Move, Droplets, Database, Compass } from 'lucide-react';

const SensorView: React.FC = () => {
  const sensors = [
    {
      id: 'ppg',
      name: 'Pulse Oximeter (PPG)',
      icon: <Zap className="text-cyan-400" />,
      description: 'Optical sensor suite utilizing multi-wavelength LED arrays to measure arterial oxygen saturation and peripheral blood flow volume.',
      specs: [
        { label: 'Wavelength', val: '660nm / 940nm' },
        { label: 'Precision', val: '±1.5% SpO2' },
        { label: 'Sampling', val: '250Hz' }
      ],
      detail: 'Photoplethysmography tracks the volumetric changes in blood vessels at the skin surface to derive heart rate and oxygen sat.'
    },
    {
      id: 'nirs',
      name: 'NIRS Spectroscopy',
      icon: <Waves className="text-indigo-400" />,
      description: 'Near-Infrared Spectroscopy for deep-tissue monitoring. Measures real-time muscle and cerebral oxygenation (SmO2).',
      specs: [
        { label: 'Depth', val: '15-25mm' },
        { label: 'Channels', val: 'Quad-Source' },
        { label: 'Spectrum', val: '760-850nm' }
      ],
      detail: 'Utilizes the varying absorption rates of oxy- and deoxy-hemoglobin to calculate localized tissue metabolic state.'
    },
    {
      id: 'ecg',
      name: 'Electrocardiogram (ECG)',
      icon: <Activity className="text-orb-accent" />,
      description: 'Dry-contact electrode array providing high-fidelity electrical heart signal acquisition for BPM and HRV analysis.',
      specs: [
        { label: 'Lead Type', val: 'Bi-Polar III' },
        { label: 'CMRR', val: '110dB' },
        { label: 'Bandwidth', val: '0.05-150Hz' }
      ],
      detail: 'Detects minute electrical potentials generated by heart muscle depolarization, providing the baseline for PhysioCore metrics.'
    },
    {
      id: 'temp',
      name: 'Thermal Regulation',
      icon: <Thermometer className="text-rose-400" />,
      description: 'Medical-grade NTC thermistor sensor tracking subtle shifts in peripheral skin temperature for heat regulation assessment.',
      specs: [
        { label: 'Accuracy', val: '±0.05°C' },
        { label: 'Range', val: '28-42°C' },
        { label: 'Response', val: '< 2.0s' }
      ],
      detail: 'Monitors vasodilation and metabolic heat dissipation patterns to predict thermal stress and recovery cycles.'
    },
    {
      id: 'imu',
      name: 'Inertial Measurement (IMU)',
      icon: <Compass className="text-amber-400" />,
      description: 'High-precision 6-axis movement tracking system. Detects micro-tremors, kinetic patterns, and posture to assess motion, fatigue, and sleep stages.',
      specs: [
        { label: 'Axes', val: '6 (Accel/Gyro)' },
        { label: 'Range', val: '±16g / 2k dps' },
        { label: 'Rate', val: '400Hz' }
      ],
      detail: 'Analyzes actigraphy and postural stability to distinguish between operational fatigue and circadian sleep cycles.'
    },
    {
      id: 'eda',
      name: 'Electrodermal Activity (EDA)',
      icon: <Droplets className="text-emerald-400" />,
      description: 'Galvanic Skin Response (GSR) sensor measuring sweat gland activity. Critical for quantifying sympathetic nervous system arousal, stress, and sleep depth.',
      specs: [
        { label: 'Sensitivity', val: '0.01μS' },
        { label: 'Resolution', val: '12-bit ADC' },
        { label: 'Electrodes', val: 'Ag/AgCl' }
      ],
      detail: 'Maps micro-conductance shifts on the epidermis to correlate biometric spikes with emotional and cognitive stress triggers.'
    },
    {
      id: 'perfusion',
      name: 'Perfusion Index (PI)',
      icon: <Move className="text-blue-400" />,
      description: 'Specialized sensors quantifying the ratio of pulsatile blood flow to static blood. Measures blood flow strength and peripheral circulation efficiency.',
      specs: [
        { label: 'Range', val: '0.02% - 20%' },
        { label: 'Correlation', val: 'Flow-Linked' },
        { label: 'Update', val: 'Real-time' }
      ],
      detail: 'Monitors the quality of peripheral circulation, providing early indicators of autonomic nervous system shifts or environmental stress.'
    },
    {
      id: 'bioimpedance',
      name: 'Bioimpedance (BIA)',
      icon: <Database className="text-purple-400" />,
      description: 'Multi-frequency electrical impedance analysis used to measure intra- and extra-cellular fluid distribution and body composition.',
      specs: [
        { label: 'Frequency', val: '50 / 100 kHz' },
        { label: 'Precision', val: '0.1% accuracy' },
        { label: 'Metric', val: 'Fluid Mapping' }
      ],
      detail: 'Tracks systemic hydration levels and fluid shifts across tissue compartments to detect signs of physiological strain or dehydration.'
    }
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-16 py-12">
      <div className="text-center space-y-6">
        <h2 className="text-5xl font-bold tracking-tighter text-white uppercase">Sensor Suite manifest</h2>
        <div className="w-16 h-1 bg-orb-accent mx-auto"></div>
        <p className="text-orb-muted text-[11px] font-bold uppercase tracking-[0.4em] max-w-xl mx-auto opacity-60">
          Hardware configuration for tactical bio-telemetry link. V8.0 Full Manifest.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pb-20">
        {sensors.map((sensor, idx) => (
          <motion.div 
            key={sensor.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.05 }}
            className="glass p-10 rounded-[2.5rem] border border-white/5 hover:border-orb-accent/30 transition-all group relative overflow-hidden bg-black/40"
          >
            <div className="flex items-start justify-between mb-8">
              <div className="p-4 bg-white/5 rounded-2xl group-hover:scale-110 transition-transform duration-500">
                {sensor.icon}
              </div>
              <div className="flex items-center gap-2 px-4 py-1.5 bg-emerald-500/10 border border-emerald-500/20 rounded-md">
                 <ShieldCheck size={10} className="text-emerald-500" />
                 <span className="text-[8px] font-black text-emerald-500 uppercase tracking-widest">Active_Link</span>
              </div>
            </div>

            <h3 className="text-xl font-bold text-white mb-4 tracking-tight">{sensor.name}</h3>
            <p className="text-orb-muted text-[12px] leading-relaxed mb-8 opacity-70 italic">
              {sensor.description}
            </p>

            <div className="grid grid-cols-3 gap-4 mb-10 border-y border-white/5 py-6">
              {sensor.specs.map(spec => (
                <div key={spec.label}>
                  <p className="text-[8px] font-black uppercase tracking-widest text-orb-muted/40 mb-1">{spec.label}</p>
                  <p className="text-[11px] font-bold text-orb-accent font-mono">{spec.val}</p>
                </div>
              ))}
            </div>

            <div className="flex items-start gap-3 opacity-40 group-hover:opacity-100 transition-opacity">
               <Info size={12} className="text-orb-muted shrink-0 mt-0.5" />
               <p className="text-[9px] font-medium text-orb-muted leading-normal uppercase tracking-wider">{sensor.detail}</p>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
};

export default SensorView;
